config/routes.rb
Beanbook::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: :destroy do
    resources :posts, except: [:index, :new, :show]
    resources :friends, only: :index
    resources :friendships, only: [:create, :update, :destroy]
    resources :photos
    resources :tags, only: [:index, :create, :destroy]
    resources :user_likes, only: [:update, :destroy] # this is a little hacky, see user_likes controller and user_likes/_form
  end

  resources :comments, only: [:create, :destroy]
  resources :conversations, except: [:new, :edit, :destroy]
  resources :posts, only: :show
  resources :notifications, only: :index

  root to: "feeds#show"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :user_id, :body, :commentable_id, :commentable_type

  validates :user_id, :body, :commentable_id, :commentable_type, presence: true
  validates :commentable_type, inclusion: {in: %w( Photo Post )}
  validate :can_only_comment_on_friends_objects

  after_create :send_notification

  belongs_to :commentable, polymorphic: true

  has_many :user_likes, as: :likable, dependent: :destroy

  has_many :notifications, as: :notifiable, dependent: :destroy

  belongs_to :author, class_name: "User", foreign_key: :user_id

  private

    def send_notification
      n = Notification.new(
        sender_id: user_id,
        notifiable_id: id,
        notifiable_type: "Comment",
        message: "#{User.find(user_id).name} commented on your #{commentable.class.to_s.downcase}!",
      )

      if commentable.class == Photo
        recipient_id = commentable.user_id
      elsif commentable.class == Post
        recipient_id = commentable.author_id
      end

      return if user_id == recipient_id # no need to send a notification to yourself

      n.recipient_id = recipient_id
      n.save
    end

    def can_only_comment_on_friends_objects
      commentable = self.commentable

      if !commentable
        errors.add("That", "does not exist")
      end

      friends = User.find(user_id).friends
      commenter = User.find(user_id)

      if commentable_type == "Photo"
        unless user_id == commentable.user_id || friends.include?(User.find(commentable.user_id))
          errors.add(commentable_type, "must belong to your friend")
        end

      elsif commentable_type == "Post"
        unless user_id == commentable.author_id || friends.include?(User.find(commentable.author_id))
          errors.add(commentable_type, "must belong to your friend")
        end
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #  eventually ajaxify

  def create # should take greater caution here for non-js requests
    comment = Comment.new(params[:comment])
    comment.user_id = current_user.id

    if request.xhr?
      if comment.save
        render partial: 'comments/show', locals: {comment: comment}
      else
        flash[:errors] = comment.errors.full_messages
        redirect_to root_url
      end
    else
      redirect_to root_url
    end
  end

  def destroy
    if Comment.find(params[:id]).destroy && request.xhr?
      render json: {success: true}
    else
      redirect_to root_url
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<% user = (object.class == Post) ? object.author : object.user %>
<% if current_user == user || current_user.friends.include?(user) %>

<h4>New Comment</h4>
<form action="<%= comments_url %>" method="post" class="new-comment" data-remote="true">

  <input type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[commentable_id]" value="<%= object.id %>">

  <input type="hidden" name="comment[commentable_type]" value="<%= object.class.to_s %>">

  <input type="text" name="comment[body]">

  <input type="submit" value="Submit Comment!">
</form>

<% end %>

app/views/comments/_index.html.erb
<ul class="comments">

  <% object.comments.each do |comment| %>
    <li>
      <%= render partial: 'comments/show', locals: {comment: comment} %>
    </li>
  <% end %>

</ul>

<script>

  $(document).ready(function(event) {

    $(".new-comment").off();

    $(".new-comment").on("ajax:success", function(event, data) {
      var $comments = $(this).parent().find(".comments")
      $comments.append("<li>" + data + "</li>");
      this.reset();
    });
  });

</script>

app/views/comments/_show.html.erb
<%= comment.author.name %>: <%= comment.body %>

<% user = comment.author %>
<% if current_user == user || current_user.friends.include?(user) %>
  <%= button_to "Delete Comment", comment_url(comment), method: :delete %>
<% end %>

<%= render partial: 'user_likes/form', locals: {object: comment, type: "Comment"} %>