config/routes.rb
Beanbook::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: :destroy do
    resources :posts, except: [:index, :new, :show]
    resources :friends, only: :index
    resources :friendships, only: [:create, :update, :destroy]
    resources :photos
    resources :tags, only: [:index, :create, :destroy]
    resources :user_likes, only: [:update, :destroy] # this is a little hacky, see user_likes controller and user_likes/_form
  end

  resources :comments, only: [:create, :destroy]
  resources :conversations, except: [:new, :edit, :destroy]
  resources :posts, only: :show
  resources :notifications, only: :index

  root to: "feeds#show"
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible(
    :taggable_type,
    :taggable_id,
    :x_pos,
    :y_pos,
    :tagger_id,
    :taggee_id
  )

  validates :taggable_type, :taggable_id, :tagger_id, :taggee_id, presence: true
  validates :taggable_type, inclusion: {in: %w( Post Photo )}
  validate(
    :can_only_tag_friend,
    :can_only_tag_on_friends_objects,
    :tag_must_be_unique
  )

  after_create :send_notification

  belongs_to(
    :tagger,
    class_name: "User"
  )

  belongs_to(
    :taggee,
    class_name: "User"
  )

  belongs_to :taggable, polymorphic: true


  has_many(
    :notifications,
    as: :notifiable,
    dependent: :destroy
  )

  private

    def can_only_tag_friend
      unless User.find(tagger_id).friends.map(&:id).include?(taggee_id) || taggee_id == tagger_id
        errors.add(:taggee_id, "is not your friend")
      end
    end

    def can_only_tag_on_friends_objects
      taggable = self.taggable
      # see if taggable.user_id is either mine or one of my friends'
      if !taggable
        errors.add(taggable_type, "does not exist")
      end

      if tagger_id != taggable.user_id && !User.find(tagger_id).friends.map(&:id).include?(taggable.user_id)
        errors.add(taggable_type, "must belong to one of your friends")
      end
    end

    def tag_must_be_unique
      if Tag.find_by_taggable_type_and_taggable_id_and_taggee_id(taggable_type, taggable_id, taggee_id)
        errors.add(:tag, "already exists")
      end
    end

    def send_notification
      return if tagger_id == taggee_id

      user = User.find(tagger_id)
      Notification.create(
        recipient_id: taggee_id,
        sender_id: tagger_id,
        notifiable_id: id,
        notifiable_type: "Tag",
        message: "#{user.name} tagged you in a #{taggable_type.downcase}!"
      )
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = User.find(params[:user_id]).tags
    if request.xhr?
      render partial: 'tags/index'
    else
      render :index
    end
  end

  def create
    tag = Tag.new(params[:tag])
    tag.tagger_id = current_user.id
    if tag.save
      flash[:notice] = ["Tag saved!"]
      # hopefully I will javascript this away
      redirect_to root_url
    else
      flash[:errors] = tag.errors.full_messages
      redirect_to root_url
    end
  end

  def destroy
    Tag.find(params[:id]).destroy
    redirect_to root_url
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<form action="<%= user_tags_url(params[:user_id]) %>" method="POST">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="tag[taggee_id]" value="<%= friend.id %>">
  <input type="hidden" name="tag[taggable_id]" value="<%= params[:id] %>">
  <input type="hidden" name="tag[taggable_type]" value="<%= klass.to_s %>">
  <input type="submit" value="Tag <%= friend.first_name %>">
</form>

app/views/tags/_index.html.erb
<h2>Places You've Been Tagged</h2>
<ul>
  <% User.find(params[:user_id]).tags.each do |tag| %>
    <% taggable = tag.taggable %>
    <li>
      <!-- FOR NOW THIS IS JUST A PHOTO - IT WILL CAUSE PROBLEMS LATER -->
      <!-- I can have a conditional that checks for the url depending on the class -->
      <figure class="preview-photo">
        <a href="<%= user_photo_url(taggable.user_id, taggable.id) %>" data-remote="true">
          <%= image_tag(taggable.photo_file.url(:small)) %>
          <figcaption>
            <%= taggable.class %>
            <%= taggable.id %>
          </figcaption>
        </a>
      </figure>
    </li>
  <% end %>
</ul>

<script>

$(document).ready(function(event) {
  $(".preview-photo").off();

  $(".preview-photo").on("ajax:success", "a", function(event, data) {
    $(".content").html(data);
  });
});

</script>

app/views/tags/_tagged_users.html.erb
<h3>Tagged Users</h3>

<ul class="tagged-users">
<% object.tagged_users.each do |user| %>

  <li class="clearfix">
    <%= render(partial: 'users/preview', locals: {user: user, post: Post.new}) %>
    <% tag = Tag.find_by_taggable_type_and_taggable_id_and_taggee_id(params["controller"].capitalize.singularize, params["id"].to_i, current_user.id) %>
    <% if user.tags.include?(tag) %>
      <%= button_to "Remove Tag", user_tag_url(params[:user_id], tag), method: :delete %>
    <% end %>
  </li>

<% end %>
</ul>

app/views/tags/index.html.erb
<%= render 'tags/index' %>