config/routes.rb
Beanbook::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: :destroy do
    resources :posts, except: [:index, :new, :show]
    resources :friends, only: :index
    resources :friendships, only: [:create, :update, :destroy]
    resources :photos
    resources :tags, only: [:index, :create, :destroy]
    resources :user_likes, only: [:update, :destroy] # this is a little hacky, see user_likes controller and user_likes/_form
  end

  resources :comments, only: [:create, :destroy]
  resources :conversations, except: [:new, :edit, :destroy]
  resources :posts, only: :show
  resources :notifications, only: :index

  root to: "feeds#show"
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author_id, :recipient_id, :body

  validates :author_id, :recipient_id, :body, presence: true
  validate :author_is_friends_with_recipient, :editor_is_author

  after_create :send_notification

  belongs_to(
    :recipient,
    class_name: "User",
    foreign_key: :recipient_id,
    primary_key: :id
  )

  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id
  )

  has_many :tags, as: :taggable, dependent: :destroy

  has_many :tagged_users, through: :tags, source: :taggee

  has_many :notifications, as: :notifiable, dependent: :destroy

  has_many :user_likes, as: :likable, dependent: :destroy

  has_many(
    :comments,
    as: :commentable,
    dependent: :destroy,
    order: "created_at ASC"
  )

  private

    def author_is_friends_with_recipient
      friendship = Friendship
        .where(pending: false)
        .find_by_inbound_friend_id_and_outbound_friend_id(author_id, recipient_id)

      unless friendship || author_id == recipient_id
        # allowed to post on your own wall
        errors.add(:friendship, "must exist")
      end
    end

    def editor_is_author
      # this is happeneing before the save, so I can check if this post
      # is in the supposed author's posts
      if id && !User.find(author_id).authored_posts.map(&:id).include?(id)
        errors.add("You", "must own a post to edit it.")
      end
    end

    def send_notification
      return if recipient_id == author_id

      user = User.find(author_id)
      Notification.create(
        recipient_id: recipient_id,
        sender_id: author_id,
        notifiable_id: id,
        notifiable_type: "Post",
        message: "#{user.name} posted on your wall!"
      )
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    post = Post.new(params[:post])
    post.author_id = current_user.id
    post.recipient_id = params[:user_id]


    if post.save
      if request.xhr?
        render partial: 'posts/show', locals: {post: post}
      else
        # flash[:errors] = post.errors.full_messages
        # this doesn't really do anything
        redirect_to user_url(params[:user_id])
      end
    else
      redirect_to user_url(params[:user_id])
    end
  end

  def show
    @post = Post.find(params[:id])
    @recipient = @post.recipient

    if request.xhr?
      render partial: 'posts/show', locals: {post: @post}
    else
      render :show
    end
  end

  def edit
    @post = Post.find(params[:id])
    if request.xhr?
      render(partial: 'posts/form', locals: {post: @post, user: User.find(params[:user_id])})
    else
      render :edit
    end
  end

  def update # okay this breaks hard if there's no JS
    post = Post.find(params[:id])
    post.author_id = current_user.id # for the model validation

    if request.xhr?
      if post.update_attributes(params[:post])
        render partial: 'posts/show', locals: {post: post}
      else
        flash[:notice] = ["Your post has been updated."]
        redirect_to user_url(params[:user_id])
      end
    else
      # maybe change all the flashes to flash.now
      flash[:errors] = post.errors.full_messages
      render partial: 'layouts/errors'
    end
  end

  def destroy
    post = Post.find(params[:id])
    id = post.recipient_id
    post.destroy
    flash[:notice] = ["Your post has been deleted."]
    redirect_to user_url(id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if post.persisted? %>
  <% action = user_post_url(user, post) %>
  <% method = "PUT" %>
<% else %>
  <% action = user_posts_url(user) %>
  <% method = "" %>
<% end %>

<form action="<%= action %>" method="POST" class="new-post" data-remote="true">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="<%= method %>">

  <textarea
    placeholder="Cold pizza is better than the Cold War. Discuss."
    name="post[body]"><%= post.body %></textarea>

  <input type="submit" value="Post!">
</form>

<script>

  $(document).ready(function(event) {

    $(".new-post").off();

    $(".new-post").on("ajax:success", function(event, data) {
      $(".posts").prepend(data);
      this.reset();
    });

  });

</script>

app/views/posts/_index.html.erb
<ul class="posts">
  <% posts.each do |post| %>
    <li>
      <%= render(partial: 'posts/show', locals: {post: post}) %>
    </li>
  <% end %>
</ul>

app/views/posts/_show.html.erb
<article class="post">
  <header class="post-header">
    <% author = post.author %>
    <%= render(partial: 'users/preview', locals: {user: author, post: post}) %>
  </header>


  <p><%= post.body %></p>

  <footer class="post-footer clearfix">
    <time class="post-page-link">
      <a href="<%= post_url(post) %>">
        <%= post.created_at.to_formatted_s(:short)  %>
      </a>
    </time>

    <% if author == current_user %>
      <div class="edit-link">
        <a href="<%= edit_user_post_url(author, post) %>" data-remote="true">Edit</a>
      </div>
    <% end %>

    <% if author == current_user || current_user.id == post.recipient_id %>
      <%= button_to "Delete", user_post_url(current_user, post), method: :delete %>
    <% end %>


    <%= render partial: 'user_likes/form', locals: {object: post, type: "Post"} %>

  </footer>

  <!-- show comments -->

  <h4>Comments</h4>
  <%= render partial: 'comments/index', locals: {object: post} %>

  <%= render partial: 'comments/form', locals: {object: post} %>
</article>


<script>

  $(document).ready(function(event) {
    $(".posts").off();

    $(".posts").on("ajax:success", ".edit-link a", function(event, data) {

      var $p = $(this).parent().parent().parent().find("p");
      $p.html(data);

      $(".new-post").off();

      $(".new-post").on("ajax:success", function(event, data) {
        var newText = $(this).find("textarea").val();
        $p.html(newText);
        this.reset();
      });
    });
  });

</script>

app/views/posts/edit.html.erb
<h2>Edit your post</h2>
<%= render(partial: 'posts/form', locals: {post: @post, user: User.find(@post.recipient_id)}) %>

app/views/posts/show.html.erb
<h2>One Post on <%= @recipient.name %>'s Page</h2>

<div class="show">
  <%= render(partial: 'posts/show', locals: {post: @post}) %>
</div>


<script>

  $(document).ready(function(event) {
    $(".post").on("ajax:success", ".edit-link a", function(event, data) {

      var $p = $(this).parent().parent().parent().find("p");
      $p.html(data);

      $(".new-post").off();

      $(".new-post").on("ajax:success", function(event, data) {
        var newText = $(this).find("textarea").val();
        $p.html(newText);
      });
    });
  });

</script>