config/routes.rb
Beanbook::Application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, except: :destroy do
    resources :posts, except: [:index, :new, :show]
    resources :friends, only: :index
    resources :friendships, only: [:create, :update, :destroy]
    resources :photos
    resources :tags, only: [:index, :create, :destroy]
    resources :user_likes, only: [:update, :destroy] # this is a little hacky, see user_likes controller and user_likes/_form
  end

  resources :comments, only: [:create, :destroy]
  resources :conversations, except: [:new, :edit, :destroy]
  resources :posts, only: :show
  resources :notifications, only: :index

  root to: "feeds#show"
end

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <ul class="errors">
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_notices.html.erb
<% if flash[:notice] %>
  <ul class="notices">
  <% flash[:notice].each do |notice| %>
    <li><%= notice %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_sidebar.html.erb
<section class="sidebar">
  <% if logged_in? %>
    <a href="<%= user_url(current_user) %>" data-remote="true">Your Profile</a>
    <a href="<%= edit_user_url(current_user) %>" data-remote="true">Edit Your Profile</a>
    <a href="<%= user_friends_url(current_user) %>" data-remote="true">Your Friends</a>
    <a href="<%= user_photos_url(current_user) %>" data-remote="true">Your Photos</a>
    <a href="<%= user_tags_url(current_user) %>" data-remote="true">Your Tags</a>
    <a href="<%= new_user_photo_url(current_user) %>" data-remote="true">Upload a New Photo</a>
    <a href="<%= users_url %>" data-remote="true">Find New Friends</a>
  <% else %>
    <h2>Awesome stuff here as soon as you log in!</h2>
  <% end %>
</section>

app/views/layouts/_user-data.html.erb
<nav>
  <ul>
  <% if logged_in? %>
    <li>Hello, <a href="<%= user_url(current_user) %>" data-remote="true"><%= current_user.first_name %>!</a></li>
    <li><a href="<%= root_url %>" data-remote="true">Feed</a></li>
    <li><a href="<%= notifications_url %>" data-remote="true">Notifications</a></li>
    <li><a href="<%= conversations_url %>" data-remote="true">Messages</a></li>
    <li><%= button_to "Log out", session_url, method: :delete %></li>
  <% else %>
    <li><a href="<%= new_session_url %>">Log In</a></li>
    <li><a href="<%= new_user_url %>">Sign Up</a></li>
  <% end %>
  </ul>
</nav>

app/views/layouts/_users_index.html.erb
<ul class="friends-index">
  <% users.each do |user| %>
    <% other_button = "" %>
    <% next if user == current_user %>

    <% friendship = Friendship.find_by_inbound_friend_id_and_outbound_friend_id(current_user.id, user.id) %>

    <% if current_user.is_friends_with?(user.id) %>
      <% button = button_to "Unfriend", user_friendship_url(current_user, friendship.id), method: :delete, remote: true %>

    <% elsif current_user.inbound_pending_friends.include?(user) %>
      <% button = button_to "Accept", user_friendship_url(current_user, friendship.id), method: :put, remote: true %>
      <% other_button = button_to "Deny", user_friendship_url(current_user, friendship.id), method: :delete, remote: true %>

    <% elsif current_user.outbound_pending_friends.include?(user) %>
      <% friendship = Friendship.find_by_inbound_friend_id_and_outbound_friend_id(user.id, current_user.id) %>
      <% button = button_to "Cancel Request", user_friendship_url(current_user, friendship.id), method: :delete, remote: true %>

    <% else %>
      <% button = button_to "Friend", user_friendships_url(user), method: :post, remote: true %>
    <% end %>

    <li class="clearfix">
        <%= render(partial: 'users/preview', locals: {user: user, post: Post.new}) %>
        <span><%= button %></span>
        <span><%= other_button %></span>
    </li>
  <% end %>
</ul>

<script>

$(document).ready(function(event) {
  $(".friends-index").off();

  $(".friends-index li").on("ajax:success", "form", function(event, data) {
    $(".content").html(data);
  });
});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BeanBook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="header clearfix">
  <h1 class="logo"><a href="<%= root_url %>">BeanBook</a></h1>
  <nav><%= render 'layouts/user-data' %></nav>
</header>

<div class="page clearfix">

  <%= render 'layouts/sidebar' %>

  <section class="content">
    <%= render 'layouts/errors' %>
    <%= render 'layouts/notices' %>

    <%= yield %>
  </section>

</div>

<footer>

</footer>

</body>
</html>

<script>

  $(document).ready(function(event) {
    // do i need to worry about garbage collection?

    $("header").off();

    $("header").on("ajax:success", "a", function(event, data) {
      $(".content").html(data);
    });

    $(".sidebar").on("ajax:success", "a", function(event, data) {
      $(".content").html(data);
    });
    
    $(".logo a").off();
  });

</script>